#!/usr/bin/env python3
"""Generate a .env file for Docker Compose from a team definition JSON."""

import argparse
import json
import sys
from pathlib import Path


def generate_env(team: dict) -> str:
    """Build .env content from a team definition."""
    gateway = team.get("gateway", {})
    team_name = team.get("name", "team")
    lines = [
        "# Generated by team-deploy generate_env.py",
        "",
        "# OpenClaw image",
        "OPENCLAW_IMAGE=openclaw:local",
        "",
        "# Paths (per-team isolation)",
        f"OPENCLAW_CONFIG_DIR=~/.openclaw/{team_name}",
        f"OPENCLAW_WORKSPACE_DIR=~/.openclaw/{team_name}/workspace",
        "",
        "# Gateway",
        f"OPENCLAW_GATEWAY_TOKEN={gateway.get('token', 'team-deploy')}",
        f"OPENCLAW_GATEWAY_PORT={gateway.get('port', 18789)}",
        "OPENCLAW_GATEWAY_BIND=lan",
    ]

    graphiti = team.get("graphiti", {})
    lines += [
        "",
        "# Graphiti / Neo4j",
        f"NEO4J_PASSWORD={graphiti.get('neo4jPassword', '')}",
        f"OPENAI_API_KEY={graphiti.get('openaiApiKey', '')}",
    ]

    # Model provider API key
    model_cfg = team.get("model", {})
    lines += [
        "",
        "# Model provider",
        f"MODEL_API_KEY={model_cfg.get('apiKey', '<REPLACE>')}",
    ]

    # Discord bot tokens (one per agent)
    agents = team.get("agents", [])
    if agents:
        lines += ["", "# Discord bot tokens"]
        for agent in agents:
            var_name = "DISCORD_" + agent["id"].upper().replace("-", "_") + "_TOKEN"
            lines.append(f"{var_name}={agent.get('discordToken', '<REPLACE>')}")

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate .env for Docker Compose")
    parser.add_argument("--team-file", required=True, help="Path to team definition JSON")
    parser.add_argument("--output", required=True, help="Output path for .env file")
    args = parser.parse_args()

    path = Path(args.team_file)
    if not path.is_file():
        print(f"Error: file not found: {path}", file=sys.stderr)
        sys.exit(1)

    team = json.loads(path.read_text())
    env_content = generate_env(team)

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(env_content)
    print(f".env written to {out}")


if __name__ == "__main__":
    main()
